package com.discord.tti_manager

import B9.s
import com.discord.logging.Log
import com.discord.react.utilities.NativeArrayExtensionsKt
import com.discord.react.utilities.NativeMapExtensionsKt
import com.discord.tti_manager.react.ReactMarkerListener
import com.facebook.react.bridge.Promise
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.bridge.ReactContextBaseJavaModule
import com.facebook.react.bridge.ReactMethod
import java.util.ArrayList
import kotlin.jvm.internal.SourceDebugExtension

@SourceDebugExtension(["SMAP\nTTIManagerModule.kt\nKotlin\n*S Kotlin\n*F\n+ 1 TTIManagerModule.kt\ncom/discord/tti_manager/TTIManagerModule\n+ 2 _Collections.kt\nkotlin/collections/CollectionsKt___CollectionsKt\n*L\n1#1,97:1\n1557#2:98\n1628#2,3:99\n*S KotlinDebug\n*F\n+ 1 TTIManagerModule.kt\ncom/discord/tti_manager/TTIManagerModule\n*L\n65#1:98\n65#1:99,3\n*E\n"])
public class TTIManagerModule(reactContext: ReactApplicationContext) : ReactContextBaseJavaModule(var1) {
   private final val ttiBroadcastReceiver: TTIBroadcastReceiver = new TTIBroadcastReceiver()

   @ReactMethod
   public fun getAllNativeTimestamps(promise: Promise) {
      var var2: ArrayList;
      var var4: java.util.Iterator;
      try {
         val var3: ArrayList = TTIMetrics.INSTANCE.getTimings();
         var2 = new ArrayList(CollectionsKt.v(var3, 10));
         var4 = var3.iterator();
      } catch (var6: java.lang.Throwable) {
         var1.reject(var6);
         return;
      }

      while (true) {
         try {
            if (!var4.hasNext()) {
               break;
            }

            val var17: TTIMetrics.Timing = var4.next() as TTIMetrics.Timing;
            var2.add(
               NativeMapExtensionsKt.nativeMapOf(
                  s.a("label", var17.getLabel()),
                  s.a("timestamp", var17.getTimestamp()),
                  s.a("tag", var17.getTag()),
                  s.a("autoGenerated", var17.getAutoGenerated())
               )
            );
         } catch (var7: java.lang.Throwable) {
            var1.reject(var7);
            return;
         }
      }

      try {
         var1.resolve(NativeArrayExtensionsKt.toNativeArray$default(var2, null, 1, null));
      } catch (var5: java.lang.Throwable) {
         var1.reject(var5);
         return;
      }
   }

   public open fun getConstants(): MutableMap<String, Long> {
      val var1: TTILoggingApplication.Companion = TTILoggingApplication.Companion;
      return L.m(
         new Pair[]{
            s.a("AppOpenedTimestamp", TTILoggingApplication.Companion.getAppOpenedTimestamp$tti_manager_release()),
            s.a("ApplicationStartedTimestamp", var1.getApplicationStartedTimestamp())
         }
      );
   }

   @ReactMethod
   public fun getJSBundleTimestamps(promise: Promise) {
      try {
         val var2: ReactMarkerListener = ReactMarkerListener.INSTANCE;
         var1.resolve(
            NativeMapExtensionsKt.nativeMapOf(
               s.a("JSBundleStartedTimestamp", (double)ReactMarkerListener.INSTANCE.getBundleStartedTimestamp()),
               s.a("JSBundleLoadedTimestamp", (double)var2.getBundleLoadedTimestamp()),
               s.a("JSBundleParsedTimestamp", (double)var2.getBundleParsedTimestamp())
            )
         );
      } catch (var3: java.lang.Throwable) {
         var1.reject(var3);
         return;
      }
   }

   public open fun getName(): String {
      return "TTIManager";
   }

   public open fun initialize() {
      super.initialize();
      if (BuildConfig.logTTIMetrics) {
         val var2: TTIBroadcastReceiver.Companion = TTIBroadcastReceiver.Companion;
         val var1: ReactApplicationContext = this.getReactApplicationContext();
         var2.register(var1, this.ttiBroadcastReceiver);
      }
   }

   public open fun invalidate() {
      super.invalidate();

      try {
         if (BuildConfig.logTTIMetrics) {
            val var1: TTIBroadcastReceiver.Companion = TTIBroadcastReceiver.Companion;
            val var2: ReactApplicationContext = this.getReactApplicationContext();
            var1.unregister(var2, this.ttiBroadcastReceiver);
         }
      } catch (var3: Exception) {
      }
   }

   @ReactMethod
   public fun logToDevice(value: String) {
      Log.i$default(Log.INSTANCE, "ttidata", var1, null, 4, null);
   }

   @ReactMethod
   public fun logToDeviceEnabled(promise: Promise) {
      var1.resolve(BuildConfig.logTTIMetrics);
   }

   @ReactMethod(isBlockingSynchronousMethod = true)
   public fun runningTTIAutomation(): Boolean {
      val var1: java.lang.Boolean = BuildConfig.logTTIMetrics;
      return var1;
   }

   @ReactMethod
   public fun trackTTILogged() {
      TTIMetrics.INSTANCE.setLoggedTTI(true);
   }
}
