package com.discord.tti_manager

import java.util.ArrayList
import kotlin.jvm.internal.q

public object TTIMetrics {
   private final val timings: MutableList<com.discord.tti_manager.TTIMetrics.Timing> = new ArrayList()

   public final var loggedTTI: Boolean
      internal set

   public fun getTimings(): ArrayList<com.discord.tti_manager.TTIMetrics.Timing> {
      // $VF: Couldn't be decompiled
      // Please report this to the Vineflower issue tracker, at https://github.com/Vineflower/vineflower/issues with a copy of the class file (if you have the rights to distribute it!)
      // java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
      //   at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
      //   at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
      //   at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
      //   at java.base/java.util.Objects.checkIndex(Objects.java:385)
      //   at java.base/java.util.ArrayList.remove(ArrayList.java:551)
      //   at org.jetbrains.java.decompiler.modules.decompiler.FinallyProcessor.removeExceptionInstructionsEx(FinallyProcessor.java:1057)
      //   at org.jetbrains.java.decompiler.modules.decompiler.FinallyProcessor.verifyFinallyEx(FinallyProcessor.java:572)
      //   at org.jetbrains.java.decompiler.modules.decompiler.FinallyProcessor.iterateGraph(FinallyProcessor.java:90)
      //
      // Bytecode:
      // 00: aload 0
      // 01: monitorenter
      // 02: new java/util/ArrayList
      // 05: dup
      // 06: getstatic com/discord/tti_manager/TTIMetrics.timings Ljava/util/List;
      // 09: invokespecial java/util/ArrayList.<init> (Ljava/util/Collection;)V
      // 0c: astore 1
      // 0d: aload 0
      // 0e: monitorexit
      // 0f: aload 1
      // 10: areturn
      // 11: astore 1
      // 12: aload 0
      // 13: monitorexit
      // 14: aload 1
      // 15: athrow
   }

   public fun record(label: String, timestamp: Long = System.currentTimeMillis(), tag: String? = null, autoGenerated: Boolean = false) {
      // $VF: Couldn't be decompiled
      // Please report this to the Vineflower issue tracker, at https://github.com/Vineflower/vineflower/issues with a copy of the class file (if you have the rights to distribute it!)
      // java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
      //   at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
      //   at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
      //   at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
      //   at java.base/java.util.Objects.checkIndex(Objects.java:385)
      //   at java.base/java.util.ArrayList.remove(ArrayList.java:551)
      //   at org.jetbrains.java.decompiler.modules.decompiler.FinallyProcessor.removeExceptionInstructionsEx(FinallyProcessor.java:1057)
      //   at org.jetbrains.java.decompiler.modules.decompiler.FinallyProcessor.verifyFinallyEx(FinallyProcessor.java:572)
      //   at org.jetbrains.java.decompiler.modules.decompiler.FinallyProcessor.iterateGraph(FinallyProcessor.java:90)
      //
      // Bytecode:
      // 00: aload 0
      // 01: monitorenter
      // 02: aload 1
      // 03: ldc "label"
      // 05: invokestatic kotlin/jvm/internal/q.h (Ljava/lang/Object;Ljava/lang/String;)V
      // 08: getstatic com/discord/tti_manager/TTIMetrics.timings Ljava/util/List;
      // 0b: astore 7
      // 0d: new com/discord/tti_manager/TTIMetrics$Timing
      // 10: astore 6
      // 12: aload 6
      // 14: aload 1
      // 15: lload 2
      // 16: aload 4
      // 18: iload 5
      // 1a: invokespecial com/discord/tti_manager/TTIMetrics$Timing.<init> (Ljava/lang/String;JLjava/lang/String;Z)V
      // 1d: aload 7
      // 1f: aload 6
      // 21: invokeinterface java/util/List.add (Ljava/lang/Object;)Z 2
      // 26: pop
      // 27: aload 0
      // 28: monitorexit
      // 29: return
      // 2a: astore 1
      // 2b: aload 0
      // 2c: monitorexit
      // 2d: aload 1
      // 2e: athrow
   }

   public data class Timing(label: String, timestamp: Long, tag: String?, autoGenerated: Boolean) {
      public final val label: String
      public final val timestamp: Long
      public final val tag: String?
      public final val autoGenerated: Boolean

      init {
         q.h(var1, "label");
         super();
         this.label = var1;
         this.timestamp = var2;
         this.tag = var4;
         this.autoGenerated = var5;
      }

      public operator fun component1(): String {
         return this.label;
      }

      public operator fun component2(): Long {
         return this.timestamp;
      }

      public operator fun component3(): String? {
         return this.tag;
      }

      public operator fun component4(): Boolean {
         return this.autoGenerated;
      }

      public fun copy(label: String = var0.label, timestamp: Long = var0.timestamp, tag: String? = var0.tag, autoGenerated: Boolean = var0.autoGenerated): com.discord.tti_manager.TTIMetrics.Timing {
         q.h(var1, "label");
         return new TTIMetrics.Timing(var1, var2, var4, var5);
      }

      public override operator fun equals(other: Any?): Boolean {
         if (this === var1) {
            return true;
         } else if (var1 !is TTIMetrics.Timing) {
            return false;
         } else {
            var1 = var1;
            if (!q.c(this.label, var1.label)) {
               return false;
            } else if (this.timestamp != var1.timestamp) {
               return false;
            } else if (!q.c(this.tag, var1.tag)) {
               return false;
            } else {
               return this.autoGenerated == var1.autoGenerated;
            }
         }
      }

      public override fun hashCode(): Int {
         val var2: Int = this.label.hashCode();
         val var3: Int = java.lang.Long.hashCode(this.timestamp);
         val var1: Int;
         if (this.tag == null) {
            var1 = 0;
         } else {
            var1 = this.tag.hashCode();
         }

         return ((var2 * 31 + var3) * 31 + var1) * 31 + java.lang.Boolean.hashCode(this.autoGenerated);
      }

      public override fun toString(): String {
         val var4: java.lang.String = this.label;
         val var1: Long = this.timestamp;
         val var5: java.lang.String = this.tag;
         val var3: Boolean = this.autoGenerated;
         val var6: StringBuilder = new StringBuilder();
         var6.append("Timing(label=");
         var6.append(var4);
         var6.append(", timestamp=");
         var6.append(var1);
         var6.append(", tag=");
         var6.append(var5);
         var6.append(", autoGenerated=");
         var6.append(var3);
         var6.append(")");
         return var6.toString();
      }
   }
}
