package com.discord.tti_manager

import android.app.Activity
import com.discord.logging.Log
import com.discord.react.utilities.NativeArrayExtensionsKt
import com.discord.react.utilities.NativeMapExtensionsKt
import com.discord.tti_manager.react.ReactMarkerListener
import com.facebook.react.bridge.Promise
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.bridge.ReactContextBaseJavaModule
import com.facebook.react.bridge.ReactMethod
import ht.v
import java.util.ArrayList
import kotlin.jvm.internal.SourceDebugExtension

@SourceDebugExtension(["SMAP\nTTIManagerModule.kt\nKotlin\n*S Kotlin\n*F\n+ 1 TTIManagerModule.kt\ncom/discord/tti_manager/TTIManagerModule\n+ 2 _Collections.kt\nkotlin/collections/CollectionsKt___CollectionsKt\n*L\n1#1,111:1\n1557#2:112\n1628#2,3:113\n*S KotlinDebug\n*F\n+ 1 TTIManagerModule.kt\ncom/discord/tti_manager/TTIManagerModule\n*L\n65#1:112\n65#1:113,3\n*E\n"])
public class TTIManagerModule(reactContext: ReactApplicationContext) : ReactContextBaseJavaModule(var1) {
   public final val reactContext: ReactApplicationContext
   private final val ttiBroadcastReceiver: TTIBroadcastReceiver

   init {
      this.reactContext = var1;
      this.ttiBroadcastReceiver = new TTIBroadcastReceiver();
   }

   @JvmStatic
   fun `reportFullyDrawn$lambda$1`(var0: Activity) {
      label10:
      try {
         var0.reportFullyDrawn();
      } catch (var1: java.lang.Throwable) {
         ;
      }
   }

   @ReactMethod
   public fun getAllNativeTimestamps(promise: Promise) {
      var var2: ArrayList;
      var var17: java.util.Iterator;
      try {
         val var3: ArrayList = TTIMetrics.INSTANCE.getTimings();
         var2 = new ArrayList(CollectionsKt.w(var3, 10));
         var17 = var3.iterator();
      } catch (var6: java.lang.Throwable) {
         var1.reject(var6);
         return;
      }

      while (true) {
         try {
            if (!var17.hasNext()) {
               break;
            }

            val var4: TTIMetrics.Timing = var17.next() as TTIMetrics.Timing;
            var2.add(
               NativeMapExtensionsKt.nativeMapOf(
                  v.a("label", var4.getLabel()),
                  v.a("timestamp", var4.getTimestamp()),
                  v.a("tag", var4.getTag()),
                  v.a("autoGenerated", var4.getAutoGenerated())
               )
            );
         } catch (var7: java.lang.Throwable) {
            var1.reject(var7);
            return;
         }
      }

      try {
         var1.resolve(NativeArrayExtensionsKt.toNativeArray$default(var2, null, 1, null));
      } catch (var5: java.lang.Throwable) {
         var1.reject(var5);
         return;
      }
   }

   public override fun getConstants(): MutableMap<String, Long> {
      val var1: TTILoggingApplication.Companion = TTILoggingApplication.Companion;
      return s0.n(
         new Pair[]{
            v.a("AppOpenedTimestamp", TTILoggingApplication.Companion.getAppOpenedTimestamp$tti_manager_release()),
            v.a("ApplicationStartedTimestamp", var1.getApplicationStartedTimestamp())
         }
      );
   }

   @ReactMethod
   public fun getJSBundleTimestamps(promise: Promise) {
      try {
         val var2: ReactMarkerListener = ReactMarkerListener.INSTANCE;
         var1.resolve(
            NativeMapExtensionsKt.nativeMapOf(
               v.a("JSBundleStartedTimestamp", (double)ReactMarkerListener.INSTANCE.getBundleStartedTimestamp()),
               v.a("JSBundleLoadedTimestamp", (double)var2.getBundleLoadedTimestamp()),
               v.a("JSBundleParsedTimestamp", (double)var2.getBundleParsedTimestamp())
            )
         );
      } catch (var3: java.lang.Throwable) {
         var1.reject(var3);
         return;
      }
   }

   public override fun getName(): String {
      return "TTIManager";
   }

   public override fun initialize() {
      super.initialize();
      if (BuildConfig.logTTIMetrics) {
         val var1: TTIBroadcastReceiver.Companion = TTIBroadcastReceiver.Companion;
         val var2: ReactApplicationContext = this.getReactApplicationContext();
         var1.register(var2, this.ttiBroadcastReceiver);
      }
   }

   public override fun invalidate() {
      super.invalidate();

      try {
         if (BuildConfig.logTTIMetrics) {
            val var1: TTIBroadcastReceiver.Companion = TTIBroadcastReceiver.Companion;
            val var2: ReactApplicationContext = this.getReactApplicationContext();
            var1.unregister(var2, this.ttiBroadcastReceiver);
         }
      } catch (var3: Exception) {
      }
   }

   @ReactMethod
   public fun logToDevice(value: String) {
      Log.i$default(Log.INSTANCE, "ttidata", var1, null, 4, null);
   }

   @ReactMethod
   public fun logToDeviceEnabled(promise: Promise) {
      var1.resolve(BuildConfig.logTTIMetrics);
   }

   @ReactMethod
   public fun reportFullyDrawn() {
      val var2: Activity = this.reactContext.getCurrentActivity();
      if (var2 != null) {
         label12:
         try {
            var2.runOnUiThread(new a(var2));
         } catch (var3: java.lang.Throwable) {
            ;
         }
      }
   }

   @ReactMethod(isBlockingSynchronousMethod = true)
   public fun runningTTIAutomation(): Boolean {
      val var1: java.lang.Boolean = BuildConfig.logTTIMetrics;
      return var1;
   }

   @ReactMethod
   public fun trackTTILogged() {
      TTIMetrics.INSTANCE.setLoggedTTI(true);
   }
}
