package com.discord.chat.presentation.events

import com.discord.chat.reactevents.ChatScrollPositionEvent
import com.discord.chat.reactevents.CompleteFirstLayoutData
import com.discord.chat.reactevents.FirstLayoutData
import com.discord.chat.reactevents.InitiateEditData
import com.discord.chat.reactevents.InitiateReplyData
import com.discord.chat.reactevents.InitiateThreadData
import com.discord.chat.reactevents.LongPressAttachmentLinkData
import com.discord.chat.reactevents.LongPressAvatarData
import com.discord.chat.reactevents.LongPressChannelData
import com.discord.chat.reactevents.LongPressCommandData
import com.discord.chat.reactevents.LongPressLinkData
import com.discord.chat.reactevents.LongPressMessageEvent
import com.discord.chat.reactevents.LongPressPollImageData
import com.discord.chat.reactevents.LongPressReactionData
import com.discord.chat.reactevents.LongPressStickerData
import com.discord.chat.reactevents.LongPressUsernameData
import com.discord.chat.reactevents.MediaAttachmentPlaybackEndedData
import com.discord.chat.reactevents.MediaAttachmentPlaybackStartedData
import com.discord.chat.reactevents.TapActivityBookmarkEmbedData
import com.discord.chat.reactevents.TapActivityInstanceEmbedData
import com.discord.chat.reactevents.TapAppMessageEmbedData
import com.discord.chat.reactevents.TapAttachmentLinkData
import com.discord.chat.reactevents.TapAutoModerationActionsData
import com.discord.chat.reactevents.TapAutoModerationFeedbackData
import com.discord.chat.reactevents.TapAvatarData
import com.discord.chat.reactevents.TapButtonActionComponent
import com.discord.chat.reactevents.TapCallData
import com.discord.chat.reactevents.TapCancelUploadItemData
import com.discord.chat.reactevents.TapChannelData
import com.discord.chat.reactevents.TapChannelPromptButtonData
import com.discord.chat.reactevents.TapClanTagChipletData
import com.discord.chat.reactevents.TapCommandData
import com.discord.chat.reactevents.TapConnectionsRoleTagData
import com.discord.chat.reactevents.TapContentInventoryEntryEmbedData
import com.discord.chat.reactevents.TapCopyText
import com.discord.chat.reactevents.TapCtaButton
import com.discord.chat.reactevents.TapDismissMediaPostSharePromptData
import com.discord.chat.reactevents.TapEmojiData
import com.discord.chat.reactevents.TapFollowForumPost
import com.discord.chat.reactevents.TapForwardFooterData
import com.discord.chat.reactevents.TapGameIconData
import com.discord.chat.reactevents.TapGiftCodeAcceptData
import com.discord.chat.reactevents.TapGiftCodeEmbedData
import com.discord.chat.reactevents.TapImageData
import com.discord.chat.reactevents.TapInlineCodeEvent
import com.discord.chat.reactevents.TapInlineForwardData
import com.discord.chat.reactevents.TapInviteAcceptEvent
import com.discord.chat.reactevents.TapInviteEvent
import com.discord.chat.reactevents.TapInviteToSpeakData
import com.discord.chat.reactevents.TapJoinActivityData
import com.discord.chat.reactevents.TapLinkData
import com.discord.chat.reactevents.TapMentionData
import com.discord.chat.reactevents.TapMessageData
import com.discord.chat.reactevents.TapMessageReplyData
import com.discord.chat.reactevents.TapObscuredMediaLearnMoreData
import com.discord.chat.reactevents.TapObscuredMediaToggleData
import com.discord.chat.reactevents.TapOpTagData
import com.discord.chat.reactevents.TapPollAction
import com.discord.chat.reactevents.TapPollAnswer
import com.discord.chat.reactevents.TapPollSubmitVote
import com.discord.chat.reactevents.TapPostPreviewEmbedData
import com.discord.chat.reactevents.TapReactionData
import com.discord.chat.reactevents.TapReferralRedeemData
import com.discord.chat.reactevents.TapRemixData
import com.discord.chat.reactevents.TapRoleIconData
import com.discord.chat.reactevents.TapSafetyPolicyNoticeEmbed
import com.discord.chat.reactevents.TapSafetySystemNotificationCta
import com.discord.chat.reactevents.TapSeeMoreData
import com.discord.chat.reactevents.TapSelectActionComponent
import com.discord.chat.reactevents.TapSeparatorData
import com.discord.chat.reactevents.TapShareForumPost
import com.discord.chat.reactevents.TapShowAltTextData
import com.discord.chat.reactevents.TapSoundmojiData
import com.discord.chat.reactevents.TapStickerData
import com.discord.chat.reactevents.TapSummaryData
import com.discord.chat.reactevents.TapSummaryJumpData
import com.discord.chat.reactevents.TapSuppressNotificationsIconData
import com.discord.chat.reactevents.TapTagData
import com.discord.chat.reactevents.TapThreadEmbedEvent
import com.discord.chat.reactevents.TapTimestampEvent
import com.discord.chat.reactevents.TapUploadProgressCloseData
import com.discord.chat.reactevents.TapUsernameData
import com.discord.chat.reactevents.TapWelcomeReplyData
import com.discord.chat.reactevents.VoiceMessagePlaybackFailedData
import com.discord.media_player.reactevents.MediaPlayFinishedAnalytics
import com.discord.reactevents.ReactEvents
import kotlin.jvm.internal.G
import l8.w

internal fun createChatReactEvents(): ReactEvents {
   return new ReactEvents(
      w.a("onChatScrollPosition", G.b(ChatScrollPositionEvent.class)),
      w.a("onLongPressAttachmentLink", G.b(LongPressAttachmentLinkData.class)),
      w.a("onLongPressAvatar", G.b(LongPressAvatarData.class)),
      w.a("onLongPressMessage", G.b(LongPressMessageEvent.class)),
      w.a("onLongPressReaction", G.b(LongPressReactionData.class)),
      w.a("onLongPressSticker", G.b(LongPressStickerData.class)),
      w.a("onLongPressUsername", G.b(LongPressUsernameData.class)),
      w.a("onLongPressCommandMention", G.b(LongPressCommandData.class)),
      w.a("onLongPressChannel", G.b(LongPressChannelData.class)),
      w.a("onTapAttachmentLink", G.b(TapAttachmentLinkData.class)),
      w.a("onTapAvatar", G.b(TapAvatarData.class)),
      w.a("onTapButtonActionComponent", G.b(TapButtonActionComponent.class)),
      w.a("onTapCall", G.b(TapCallData.class)),
      w.a("onTapChannel", G.b(TapChannelData.class)),
      w.a("onTapCopyText", G.b(TapCopyText.class)),
      w.a("onTapGiftCodeAccept", G.b(TapGiftCodeAcceptData.class)),
      w.a("onTapGiftCodeEmbed", G.b(TapGiftCodeEmbedData.class)),
      w.a("onTapReferralRedeem", G.b(TapReferralRedeemData.class)),
      w.a("onTapImage", G.b(TapImageData.class)),
      w.a("onTapInviteEmbed", G.b(TapInviteEvent.class)),
      w.a("onTapInviteEmbedAccept", G.b(TapInviteAcceptEvent.class)),
      w.a("onTapJoinActivity", G.b(TapJoinActivityData.class)),
      w.a("onTapLink", G.b(TapLinkData.class)),
      w.a("onLongPressLink", G.b(LongPressLinkData.class)),
      w.a("onTapMention", G.b(TapMentionData.class)),
      w.a("onTapCommandMention", G.b(TapCommandData.class)),
      w.a("onTapMessage", G.b(TapMessageData.class)),
      w.a("onTapMessageReply", G.b(TapMessageReplyData.class)),
      w.a("onTapSummary", G.b(TapSummaryData.class)),
      w.a("onTapSummaryJump", G.b(TapSummaryJumpData.class)),
      w.a("onTapReaction", G.b(TapReactionData.class)),
      w.a("onTapRoleIcon", G.b(TapRoleIconData.class)),
      w.a("onTapGameIcon", G.b(TapGameIconData.class)),
      w.a("onTapSuppressNotificationsIcon", G.b(TapSuppressNotificationsIconData.class)),
      w.a("onTapSeeMore", G.b(TapSeeMoreData.class)),
      w.a("onInitiateReply", G.b(InitiateReplyData.class)),
      w.a("onInitiateThread", G.b(InitiateThreadData.class)),
      w.a("onInitiateEdit", G.b(InitiateEditData.class)),
      w.a("onTapConnectionsRoleTag", G.b(TapConnectionsRoleTagData.class)),
      w.a("onTapSelectActionComponent", G.b(TapSelectActionComponent.class)),
      w.a("onTapSeparator", G.b(TapSeparatorData.class)),
      w.a("onTapSticker", G.b(TapStickerData.class)),
      w.a("onTapTimestamp", G.b(TapTimestampEvent.class)),
      w.a("onTapInlineCode", G.b(TapInlineCodeEvent.class)),
      w.a("onTapThreadEmbed", G.b(TapThreadEmbedEvent.class)),
      w.a("onTapUsername", G.b(TapUsernameData.class)),
      w.a("onTapUploadProgressClose", G.b(TapUploadProgressCloseData.class)),
      w.a("onTapCancelUploadItem", G.b(TapCancelUploadItemData.class)),
      w.a("onTapWelcomeReply", G.b(TapWelcomeReplyData.class)),
      w.a("onTapInviteToSpeak", G.b(TapInviteToSpeakData.class)),
      w.a("onTapEmoji", G.b(TapEmojiData.class)),
      w.a("onTapFollowForumPost", G.b(TapFollowForumPost.class)),
      w.a("onTapShareForumPost", G.b(TapShareForumPost.class)),
      w.a("onTapReactionOverflow", G.b(TapReactionOverflow.class)),
      w.a("onTapAutoModerationActions", G.b(TapAutoModerationActionsData.class)),
      w.a("onTapAutoModerationFeedback", G.b(TapAutoModerationFeedbackData.class)),
      w.a("onTapOpTag", G.b(TapOpTagData.class)),
      w.a("onTapShowAltText", G.b(TapShowAltTextData.class)),
      w.a("onMediaAttachmentPlaybackEnded", G.b(MediaAttachmentPlaybackEndedData.class)),
      w.a("onVoiceMessagePlaybackFailed", G.b(VoiceMessagePlaybackFailedData.class)),
      w.a("onMediaAttachmentPlaybackStarted", G.b(MediaAttachmentPlaybackStartedData.class)),
      w.a("onTapActivityBookmarkEmbed", G.b(TapActivityBookmarkEmbedData.class)),
      w.a("onTapActivityInstanceEmbed", G.b(TapActivityInstanceEmbedData.class)),
      w.a("onTapAppMessageEmbed", G.b(TapAppMessageEmbedData.class)),
      w.a("onTapPostPreviewEmbed", G.b(TapPostPreviewEmbedData.class)),
      w.a("onTapDismissMediaPostSharePrompt", G.b(TapDismissMediaPostSharePromptData.class)),
      w.a("onTapTag", G.b(TapTagData.class)),
      w.a("onTapRemix", G.b(TapRemixData.class)),
      w.a("onTapChannelPromptButton", G.b(TapChannelPromptButtonData.class)),
      w.a("onTapObscuredMediaLearnMore", G.b(TapObscuredMediaLearnMoreData.class)),
      w.a("onTapObscuredMediaToggle", G.b(TapObscuredMediaToggleData.class)),
      w.a("onTapSafetyPolicyNoticeEmbed", G.b(TapSafetyPolicyNoticeEmbed.class)),
      w.a("onTapSafetySystemNotificationCta", G.b(TapSafetySystemNotificationCta.class)),
      w.a("onTapPollAnswer", G.b(TapPollAnswer.class)),
      w.a("onTapPollSubmitVote", G.b(TapPollSubmitVote.class)),
      w.a("onTapPollAction", G.b(TapPollAction.class)),
      w.a("onLongPressPollImage", G.b(LongPressPollImageData.class)),
      w.a("onTapCtaButton", G.b(TapCtaButton.class)),
      w.a("onFirstLayout", G.b(FirstLayoutData.class)),
      w.a("onCompleteFirstLayout", G.b(CompleteFirstLayoutData.class)),
      w.a("onMediaPlayFinishedAnalytics", G.b(MediaPlayFinishedAnalytics.class)),
      w.a("onTapForwardFooter", G.b(TapForwardFooterData.class)),
      w.a("onTapInlineForward", G.b(TapInlineForwardData.class)),
      w.a("onTapClanTagChiplet", G.b(TapClanTagChipletData.class)),
      w.a("onTapContentInventoryEntryEmbed", G.b(TapContentInventoryEntryEmbedData.class)),
      w.a("onTapSoundmoji", G.b(TapSoundmojiData.class))
   );
}
