name: Track

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 6 * * *"
    - cron: "30 * * * *"

permissions: write-all

jobs:
  track:
    name: track ${{ matrix.release_channel }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        release_channel: [alpha, beta, stable]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          repository: "Wumpus-Central/midroid-backend"
          ref: "main"
          token: ${{ secrets.GH_TOKEN }}
          path: "backend"

      - uses: oven-sh/setup-bun@v2
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - run: ./bootstrap.sh
        working-directory: backend

      - run: ./start.sh
        working-directory: backend
        env:
          RELEASE_CHANNEL: ${{ matrix.release_channel }}
          GITHUB_TOKEN: ${{ github.token }}
          USES_ACTIONS: "1"
